### ISSUE TITLE
Cannot connect to EV3 via USB on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by sham1917** [ev3dev/vscode-ev3dev-browser#94] opened 2020-02-03 21:43 UTC
I was working on the robot lego EV3 MicroPython with VScode. Last week, I was able to connect to the EV3 device without any problem using a USB cable. This week, I am not able to connect anymore, the device cannot be found. The connection seems to be recognized by the computer  (macOS Catalina, 10.15.3) though. I haven't changed anything but I upgraded my computer to 10.15.3 last week. I'm not sure if this is linked or not. 

I'm sorry if it's not the right place to ask, I'm new to this. Thanks for your help.

**Comment by dlech** [comment] 2020-02-04 04:06
Can you give the exact steps to reproduce the problem? It is working for me on 10.15.3 Beta (19D75a).

**Comment by sham1917** [comment] 2020-02-04 06:54
Whatever steps I take I have the same issue (it might not be related to the Catalina release?). I have flashed an sd card with microPython EV3 (following the steps detailed here https://le-www-live-s.legocdn.com/sc/media/files/ev3-micropython/ev3micropythonv100-71d3f28c59a1e766e92a59ff8500818e.pdf). Installed VScode, latest release, with EV3 MicroPython extension (which uses ev3dev-browser). I open a new project, turn on the lego, connect the lego with an USB cable to the computer. In the new project on the bottom I used to see my EV3 ready to be connected (EV3dev device browser in VSCode). But now it doesn't see anything anymore ("Searching for devices...Select a device or press ESC to cancel", no devices are shown). But the lego is recognized on the computer if I check the USB port on the System Information provided in my mac. I have tried with another lego brick but I'm facing the same issue. I haven't tried with another computer yet. Hope this helps :(

**Comment by sham1917** [comment] 2020-02-04 20:31
I was able to connect again, following the same steps (using the same sd card) and using a friend's computer (running MacOS Mojave 10.14.6). It still doesn't connect with my computer though.

**Comment by sham1917** [comment] 2020-02-07 12:12
Today, the connection worked with my computer. The only thing that changed is a new release of visual studio code (version 1.42.0). Again, I'm not 100% sure if the two events are linked or not.

**Comment by dlech** [comment] 2020-02-13 16:41
Closing since this doesn't seem to be reproducible.

**Closed by dlech** 2020-02-13 16:41 UTC
